export default {
    LIST_REQUEST: 'LIST_REQUEST',

    LIST_REQUEST_SUCCESS: 'LIST_REQUEST_SUCCESS',

    LIST_LOAD_MORE_SUCCESS: 'LIST_LOAD_MORE_SUCCESS',

    LIST_CHANGE_FILTER: 'LIST_CHANGE_FILTER',

    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    REDIRECT: 'REDIRECT',
};
